#!/usr/bin/env bash

function typeof () {
    filename=$1

    # add new filetypes here

    case $filename in
        *.pl | *.pm ) echo perl; exit ;;
        *.json ) echo json; exit ;;
        *.tmpl | *.tt ) echo template; exit ;;
        *.t ) echo test; exit ;;
        *.sh ) echo bash; exit ;; # probably, anyway :D
        *.yml | *.yaml ) echo yaml; exit;;
        # *.js ) echo javascript; exit;;
    esac

    # for files with no extension, lets look at the shbang line
    shbang=$(head -1 $1)
    case $shbang in
        '#!'*perl )
            echo perl; exit ;;
        '#!'*bash )
            echo bash; exit ;;
    esac

    echo "unhandled";
}

if [ -f cpanfile ]
then
    carton="carton exec"
fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

badFiles=""

# if you change this to $(some git command) | while (whatever)
# remember that the shell variables in the while loop are
# in a different process, and you will not be able to access
# them outside of it without significant shell hackery.

for file in $(git diff --cached --name-only $against)
do
    # bit of a hack, but it'll do
    if [ $(git status --porcelain $file | sed -e "s;$file;;" | sed -e 's/ //g' ) == "D" ]
    then
        echo ">>> pre-commit: skipping deleted file $file"; continue
    fi

    type=$(typeof "$file")
    if [ 'unhandled' == $type ]
    then
        echo ">>> pre-commit: skipping unhandled file $file"; continue
    fi

    echo ">>> pre-commit: checking $type file $file"
    BAD=false
    case $type in
        # file type detected in function typeof above
        test )
            # we could fall through and syntax check the Perl, but trying to run it
            # will essentially do that anyway :D
            $carton prove -l $file || BAD=true
            ;;
        perl )
            $carton perl -cw $file || BAD=true
            ;;
        json )
            json_pp -t null < $file && echo "JSON syntax OK" || BAD=true
            ;;
        bash )
            # note this WILL NOT check external commands missing from your PATH
            bash -n $file && echo "Bash syntax OK" || BAD=true
            ;;
        yaml )
            yamllint $file
            ;;
        * )
            echo "detected but unhandled file type $type: assume OK"
            ;;
    esac

    if $BAD
    then
        if [ -z $badFiles ]
        then
            badFiles=$file
        else
            badFiles="$badFiles;$file"
        fi
    fi
done
if [ -z "$badFiles" ]
then
    echo ">>> pre-commit: all files OK"
    exit 0;
else
    echo
    echo '>>> pre-commit: ### Aborting commit.  Failed checks: ###'
    for file in $(echo $badFiles | tr ';' ' ')
    do
        echo "    $file"
    done
    echo
    echo "If you are ABSOLUTELY 100% sure that you can skip these pre-commit tests, add:";
    echo "       --no-verify";
    echo "to your last command to skip them, and indicate clearly you have done so in the PR.";
    exit 1;
fi
